Fix Jenkinsfile syntax and Windows compatibility

diff --git a/jenkins/Jenkinsfile b/jenkins/Jenkinsfile
--- a/jenkins/Jenkinsfile
+++ b/jenkins/Jenkinsfile
@@ -6,44 +6,45 @@ pipeline {
         CONTAINER_NAME = "fraud-api"
     }
 
-    stage('Checkout Code') {
-    steps {
-        git branch: 'main',
-            url: 'https://github.com/rp7398/real-time-fraud-detection.git',
-            credentialsId: 'github-token'
-    }
-}
+    stages {
 
-        stage('Install Dependencies') {
+        stage('Checkout Code') {
             steps {
-                sh 'pip install -r requirements.txt'
+                git branch: 'main',
+                    url: 'https://github.com/rp7398/real-time-fraud-detection.git'
             }
         }
 
-        stage('Run Data Pipeline') {
+        stage('Install Dependencies') {
             steps {
-                sh 'python src/ingestion/ingest.py'
-                sh 'python src/etl/transform.py'
+                bat 'pip install -r requirements.txt'
+            }
+        }
+
+        stage('Run ETL Pipeline') {
+            steps {
+                bat 'python src/ingestion/ingest.py'
+                bat 'python src/etl/transform.py'
             }
         }
 
         stage('Train Model') {
             steps {
-                sh 'python src/training/train_model.py'
+                bat 'python src/training/train_model.py'
             }
         }
 
         stage('Build Docker Image') {
             steps {
-                sh 'docker build -t $IMAGE_NAME -f docker/Dockerfile .'
+                bat 'docker build -t %IMAGE_NAME% -f docker/Dockerfile .'
             }
         }
 
         stage('Deploy Container') {
             steps {
-                sh '''
-                docker rm -f $CONTAINER_NAME || true
-                docker run -d -p 5000:5000 --name $CONTAINER_NAME $IMAGE_NAME
+                bat '''
+                docker rm -f %CONTAINER_NAME% || exit 0
+                docker run -d -p 5000:5000 --name %CONTAINER_NAME% %IMAGE_NAME%
                 '''
             }
         }
@@ -51,10 +52,10 @@ pipeline {
 
     post {
         success {
-            echo "Fraud Detection API deployed successfully"
+            echo 'Pipeline executed successfully'
         }
         failure {
-            echo "Pipeline failed"
+            echo 'Pipeline failed'
         }
     }
 }
